@token = 1|9JPmFdS0kvZ18vcCiqPMzlxP3bq0UlBN8AwOZddP4ff4ba37
@host = http://localhost/api

### get all user alerts (paginated)
GET {{host}}/alerts
Authorization: Bearer {{token}}
Accept: application/json

### create a new price alert
POST {{host}}/alerts
Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json

{
    "cryptocurrency_id": 1,
    "target_price": 20000.00,
    "direction": "below"
}

### delete a specific alert
DELETE {{host}}/alerts/3
Authorization: Bearer {{token}}
Accept: application/json

### get all market prices (Cached)
GET {{host}}/market
Accept: application/json
